/* 
 * Statistics Service
 *
 * Statistics Service
 *
 * OpenAPI spec version: 9.0.000.00.dev
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Genesys.Statistics.Client;

namespace Genesys.Statistics.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INotificationsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// CometD connect
        /// </summary>
        /// <remarks>
        /// CometD connect, see https://docs.cometd.org/current/reference/#_bayeux_meta_connect
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void ConnectUsingPOST ();

        /// <summary>
        /// CometD connect
        /// </summary>
        /// <remarks>
        /// CometD connect, see https://docs.cometd.org/current/reference/#_bayeux_meta_connect
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ConnectUsingPOSTWithHttpInfo ();
        /// <summary>
        /// CometD disconnect
        /// </summary>
        /// <remarks>
        /// CometD disconnect, see https://docs.cometd.org/current/reference/#_bayeux_meta_disconnect
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void DisconnectUsingPOST ();

        /// <summary>
        /// CometD disconnect
        /// </summary>
        /// <remarks>
        /// CometD disconnect, see https://docs.cometd.org/current/reference/#_bayeux_meta_disconnect
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DisconnectUsingPOSTWithHttpInfo ();
        /// <summary>
        /// CometD handshake
        /// </summary>
        /// <remarks>
        /// CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_handshake
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void HandshakeUsingPOST ();

        /// <summary>
        /// CometD handshake
        /// </summary>
        /// <remarks>
        /// CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_handshake
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> HandshakeUsingPOSTWithHttpInfo ();
        /// <summary>
        /// CometD endpoint
        /// </summary>
        /// <remarks>
        /// CometD endpoint
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void NotificationsUsingPOST ();

        /// <summary>
        /// CometD endpoint
        /// </summary>
        /// <remarks>
        /// CometD endpoint
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> NotificationsUsingPOSTWithHttpInfo ();
        /// <summary>
        /// CometD subscribe to channel
        /// </summary>
        /// <remarks>
        /// CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_subscribe  Current channels:  &lt;b&gt;/statistics/v3/service&lt;/b&gt; - information about service state  &lt;b&gt;/statistics/v3/updates&lt;/b&gt; - statistics updates  
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void SubscribeUsingPOST ();

        /// <summary>
        /// CometD subscribe to channel
        /// </summary>
        /// <remarks>
        /// CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_subscribe  Current channels:  &lt;b&gt;/statistics/v3/service&lt;/b&gt; - information about service state  &lt;b&gt;/statistics/v3/updates&lt;/b&gt; - statistics updates  
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> SubscribeUsingPOSTWithHttpInfo ();
        /// <summary>
        /// CometD unsubscribe
        /// </summary>
        /// <remarks>
        /// unscubscribe from channels, see https://docs.cometd.org/current/reference/#_bayeux_meta_unsubscribe
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void UnsubscribeUsingPOST ();

        /// <summary>
        /// CometD unsubscribe
        /// </summary>
        /// <remarks>
        /// unscubscribe from channels, see https://docs.cometd.org/current/reference/#_bayeux_meta_unsubscribe
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UnsubscribeUsingPOSTWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// CometD connect
        /// </summary>
        /// <remarks>
        /// CometD connect, see https://docs.cometd.org/current/reference/#_bayeux_meta_connect
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ConnectUsingPOSTAsync ();

        /// <summary>
        /// CometD connect
        /// </summary>
        /// <remarks>
        /// CometD connect, see https://docs.cometd.org/current/reference/#_bayeux_meta_connect
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ConnectUsingPOSTAsyncWithHttpInfo ();
        /// <summary>
        /// CometD disconnect
        /// </summary>
        /// <remarks>
        /// CometD disconnect, see https://docs.cometd.org/current/reference/#_bayeux_meta_disconnect
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DisconnectUsingPOSTAsync ();

        /// <summary>
        /// CometD disconnect
        /// </summary>
        /// <remarks>
        /// CometD disconnect, see https://docs.cometd.org/current/reference/#_bayeux_meta_disconnect
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DisconnectUsingPOSTAsyncWithHttpInfo ();
        /// <summary>
        /// CometD handshake
        /// </summary>
        /// <remarks>
        /// CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_handshake
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task HandshakeUsingPOSTAsync ();

        /// <summary>
        /// CometD handshake
        /// </summary>
        /// <remarks>
        /// CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_handshake
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> HandshakeUsingPOSTAsyncWithHttpInfo ();
        /// <summary>
        /// CometD endpoint
        /// </summary>
        /// <remarks>
        /// CometD endpoint
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task NotificationsUsingPOSTAsync ();

        /// <summary>
        /// CometD endpoint
        /// </summary>
        /// <remarks>
        /// CometD endpoint
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> NotificationsUsingPOSTAsyncWithHttpInfo ();
        /// <summary>
        /// CometD subscribe to channel
        /// </summary>
        /// <remarks>
        /// CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_subscribe  Current channels:  &lt;b&gt;/statistics/v3/service&lt;/b&gt; - information about service state  &lt;b&gt;/statistics/v3/updates&lt;/b&gt; - statistics updates  
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task SubscribeUsingPOSTAsync ();

        /// <summary>
        /// CometD subscribe to channel
        /// </summary>
        /// <remarks>
        /// CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_subscribe  Current channels:  &lt;b&gt;/statistics/v3/service&lt;/b&gt; - information about service state  &lt;b&gt;/statistics/v3/updates&lt;/b&gt; - statistics updates  
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SubscribeUsingPOSTAsyncWithHttpInfo ();
        /// <summary>
        /// CometD unsubscribe
        /// </summary>
        /// <remarks>
        /// unscubscribe from channels, see https://docs.cometd.org/current/reference/#_bayeux_meta_unsubscribe
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UnsubscribeUsingPOSTAsync ();

        /// <summary>
        /// CometD unsubscribe
        /// </summary>
        /// <remarks>
        /// unscubscribe from channels, see https://docs.cometd.org/current/reference/#_bayeux_meta_unsubscribe
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UnsubscribeUsingPOSTAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class NotificationsApi : INotificationsApi
    {
        private Genesys.Statistics.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NotificationsApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Genesys.Statistics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public NotificationsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Genesys.Statistics.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Genesys.Statistics.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// CometD connect CometD connect, see https://docs.cometd.org/current/reference/#_bayeux_meta_connect
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void ConnectUsingPOST ()
        {
             ConnectUsingPOSTWithHttpInfo();
        }

        /// <summary>
        /// CometD connect CometD connect, see https://docs.cometd.org/current/reference/#_bayeux_meta_connect
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> ConnectUsingPOSTWithHttpInfo ()
        {

            var localVarPath = "/notifications/connect";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ConnectUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD connect CometD connect, see https://docs.cometd.org/current/reference/#_bayeux_meta_connect
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ConnectUsingPOSTAsync ()
        {
             await ConnectUsingPOSTAsyncWithHttpInfo();

        }

        /// <summary>
        /// CometD connect CometD connect, see https://docs.cometd.org/current/reference/#_bayeux_meta_connect
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ConnectUsingPOSTAsyncWithHttpInfo ()
        {

            var localVarPath = "/notifications/connect";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ConnectUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD disconnect CometD disconnect, see https://docs.cometd.org/current/reference/#_bayeux_meta_disconnect
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void DisconnectUsingPOST ()
        {
             DisconnectUsingPOSTWithHttpInfo();
        }

        /// <summary>
        /// CometD disconnect CometD disconnect, see https://docs.cometd.org/current/reference/#_bayeux_meta_disconnect
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DisconnectUsingPOSTWithHttpInfo ()
        {

            var localVarPath = "/notifications/disconnect";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DisconnectUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD disconnect CometD disconnect, see https://docs.cometd.org/current/reference/#_bayeux_meta_disconnect
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DisconnectUsingPOSTAsync ()
        {
             await DisconnectUsingPOSTAsyncWithHttpInfo();

        }

        /// <summary>
        /// CometD disconnect CometD disconnect, see https://docs.cometd.org/current/reference/#_bayeux_meta_disconnect
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DisconnectUsingPOSTAsyncWithHttpInfo ()
        {

            var localVarPath = "/notifications/disconnect";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DisconnectUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD handshake CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_handshake
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void HandshakeUsingPOST ()
        {
             HandshakeUsingPOSTWithHttpInfo();
        }

        /// <summary>
        /// CometD handshake CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_handshake
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> HandshakeUsingPOSTWithHttpInfo ()
        {

            var localVarPath = "/notifications/handshake";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HandshakeUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD handshake CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_handshake
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task HandshakeUsingPOSTAsync ()
        {
             await HandshakeUsingPOSTAsyncWithHttpInfo();

        }

        /// <summary>
        /// CometD handshake CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_handshake
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> HandshakeUsingPOSTAsyncWithHttpInfo ()
        {

            var localVarPath = "/notifications/handshake";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HandshakeUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD endpoint CometD endpoint
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void NotificationsUsingPOST ()
        {
             NotificationsUsingPOSTWithHttpInfo();
        }

        /// <summary>
        /// CometD endpoint CometD endpoint
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> NotificationsUsingPOSTWithHttpInfo ()
        {

            var localVarPath = "/notifications";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("NotificationsUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD endpoint CometD endpoint
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task NotificationsUsingPOSTAsync ()
        {
             await NotificationsUsingPOSTAsyncWithHttpInfo();

        }

        /// <summary>
        /// CometD endpoint CometD endpoint
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> NotificationsUsingPOSTAsyncWithHttpInfo ()
        {

            var localVarPath = "/notifications";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("NotificationsUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD subscribe to channel CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_subscribe  Current channels:  &lt;b&gt;/statistics/v3/service&lt;/b&gt; - information about service state  &lt;b&gt;/statistics/v3/updates&lt;/b&gt; - statistics updates  
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void SubscribeUsingPOST ()
        {
             SubscribeUsingPOSTWithHttpInfo();
        }

        /// <summary>
        /// CometD subscribe to channel CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_subscribe  Current channels:  &lt;b&gt;/statistics/v3/service&lt;/b&gt; - information about service state  &lt;b&gt;/statistics/v3/updates&lt;/b&gt; - statistics updates  
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> SubscribeUsingPOSTWithHttpInfo ()
        {

            var localVarPath = "/notifications/subscribe";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscribeUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD subscribe to channel CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_subscribe  Current channels:  &lt;b&gt;/statistics/v3/service&lt;/b&gt; - information about service state  &lt;b&gt;/statistics/v3/updates&lt;/b&gt; - statistics updates  
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task SubscribeUsingPOSTAsync ()
        {
             await SubscribeUsingPOSTAsyncWithHttpInfo();

        }

        /// <summary>
        /// CometD subscribe to channel CometD handshake, see https://docs.cometd.org/current/reference/#_bayeux_meta_subscribe  Current channels:  &lt;b&gt;/statistics/v3/service&lt;/b&gt; - information about service state  &lt;b&gt;/statistics/v3/updates&lt;/b&gt; - statistics updates  
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> SubscribeUsingPOSTAsyncWithHttpInfo ()
        {

            var localVarPath = "/notifications/subscribe";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscribeUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD unsubscribe unscubscribe from channels, see https://docs.cometd.org/current/reference/#_bayeux_meta_unsubscribe
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void UnsubscribeUsingPOST ()
        {
             UnsubscribeUsingPOSTWithHttpInfo();
        }

        /// <summary>
        /// CometD unsubscribe unscubscribe from channels, see https://docs.cometd.org/current/reference/#_bayeux_meta_unsubscribe
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> UnsubscribeUsingPOSTWithHttpInfo ()
        {

            var localVarPath = "/notifications/unsubscribe";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UnsubscribeUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// CometD unsubscribe unscubscribe from channels, see https://docs.cometd.org/current/reference/#_bayeux_meta_unsubscribe
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UnsubscribeUsingPOSTAsync ()
        {
             await UnsubscribeUsingPOSTAsyncWithHttpInfo();

        }

        /// <summary>
        /// CometD unsubscribe unscubscribe from channels, see https://docs.cometd.org/current/reference/#_bayeux_meta_unsubscribe
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> UnsubscribeUsingPOSTAsyncWithHttpInfo ()
        {

            var localVarPath = "/notifications/unsubscribe";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UnsubscribeUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
