/* 
 * Statistics Service API
 *
 * Statistics API
 *
 * OpenAPI spec version: 9.0.000.00.333
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Genesys.Statistics.Client;
using Genesys.Statistics.Model;

namespace Genesys.Statistics.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatisticsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Opens the stat server subscription for the specified set of statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">definitions for statistics which are to be opened with stat server</param>
        /// <returns>ApiResponse</returns>
        ApiResponse CreateSubscription (string statistics);

        /// <summary>
        /// Opens the stat server subscription for the specified set of statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">definitions for statistics which are to be opened with stat server</param>
        /// <returns>ApiResponse of ApiResponse</returns>
        ApiResponse<ApiResponse> CreateSubscriptionWithHttpInfo (string statistics);
        /// <summary>
        /// Deletes the specified stat server subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to delete</param>
        /// <returns>ApiResponse</returns>
        ApiResponse DeleteSubscription (string id);

        /// <summary>
        /// Deletes the specified stat server subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to delete</param>
        /// <returns>ApiResponse of ApiResponse</returns>
        ApiResponse<ApiResponse> DeleteSubscriptionWithHttpInfo (string id);
        /// <summary>
        /// Peeks the value of specified statistic
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statisticName">name of statistic to be peeked</param>
        /// <param name="objectId">id of object for which statistic to be peeked</param>
        /// <param name="objectType">type of object for which statistic to be peeked</param>
        /// <returns>ApiResponse</returns>
        ApiResponse GetStatValue (string statisticName, string objectId, string objectType);

        /// <summary>
        /// Peeks the value of specified statistic
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statisticName">name of statistic to be peeked</param>
        /// <param name="objectId">id of object for which statistic to be peeked</param>
        /// <param name="objectType">type of object for which statistic to be peeked</param>
        /// <returns>ApiResponse of ApiResponse</returns>
        ApiResponse<ApiResponse> GetStatValueWithHttpInfo (string statisticName, string objectId, string objectType);
        /// <summary>
        /// Peeks the values of specified statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">A set of definitions for statistics which are to be peeked from stat server</param>
        /// <returns>ApiResponse</returns>
        ApiResponse GetStatValues (string statistics);

        /// <summary>
        /// Peeks the values of specified statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">A set of definitions for statistics which are to be peeked from stat server</param>
        /// <returns>ApiResponse of ApiResponse</returns>
        ApiResponse<ApiResponse> GetStatValuesWithHttpInfo (string statistics);
        /// <summary>
        /// Peeks the values of statistics opened inside the specified subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to peek</param>
        /// <param name="statisticIds">The ids of the statistics to peek (optional)</param>
        /// <returns>ApiResponse</returns>
        ApiResponse PeekSubscriptionStats (string id, string statisticIds = null);

        /// <summary>
        /// Peeks the values of statistics opened inside the specified subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to peek</param>
        /// <param name="statisticIds">The ids of the statistics to peek (optional)</param>
        /// <returns>ApiResponse of ApiResponse</returns>
        ApiResponse<ApiResponse> PeekSubscriptionStatsWithHttpInfo (string id, string statisticIds = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Opens the stat server subscription for the specified set of statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">definitions for statistics which are to be opened with stat server</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse> CreateSubscriptionAsync (string statistics);

        /// <summary>
        /// Opens the stat server subscription for the specified set of statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">definitions for statistics which are to be opened with stat server</param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiResponse>> CreateSubscriptionAsyncWithHttpInfo (string statistics);
        /// <summary>
        /// Deletes the specified stat server subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to delete</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse> DeleteSubscriptionAsync (string id);

        /// <summary>
        /// Deletes the specified stat server subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to delete</param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiResponse>> DeleteSubscriptionAsyncWithHttpInfo (string id);
        /// <summary>
        /// Peeks the value of specified statistic
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statisticName">name of statistic to be peeked</param>
        /// <param name="objectId">id of object for which statistic to be peeked</param>
        /// <param name="objectType">type of object for which statistic to be peeked</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse> GetStatValueAsync (string statisticName, string objectId, string objectType);

        /// <summary>
        /// Peeks the value of specified statistic
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statisticName">name of statistic to be peeked</param>
        /// <param name="objectId">id of object for which statistic to be peeked</param>
        /// <param name="objectType">type of object for which statistic to be peeked</param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiResponse>> GetStatValueAsyncWithHttpInfo (string statisticName, string objectId, string objectType);
        /// <summary>
        /// Peeks the values of specified statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">A set of definitions for statistics which are to be peeked from stat server</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse> GetStatValuesAsync (string statistics);

        /// <summary>
        /// Peeks the values of specified statistics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">A set of definitions for statistics which are to be peeked from stat server</param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiResponse>> GetStatValuesAsyncWithHttpInfo (string statistics);
        /// <summary>
        /// Peeks the values of statistics opened inside the specified subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to peek</param>
        /// <param name="statisticIds">The ids of the statistics to peek (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse> PeekSubscriptionStatsAsync (string id, string statisticIds = null);

        /// <summary>
        /// Peeks the values of statistics opened inside the specified subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to peek</param>
        /// <param name="statisticIds">The ids of the statistics to peek (optional)</param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiResponse>> PeekSubscriptionStatsAsyncWithHttpInfo (string id, string statisticIds = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StatisticsApi : IStatisticsApi
    {
        private Genesys.Statistics.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StatisticsApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Genesys.Statistics.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StatisticsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Genesys.Statistics.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Genesys.Statistics.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Opens the stat server subscription for the specified set of statistics 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">definitions for statistics which are to be opened with stat server</param>
        /// <returns>ApiResponse</returns>
        public ApiResponse CreateSubscription (string statistics)
        {
             ApiResponse<ApiResponse> localVarResponse = CreateSubscriptionWithHttpInfo(statistics);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Opens the stat server subscription for the specified set of statistics 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">definitions for statistics which are to be opened with stat server</param>
        /// <returns>ApiResponse of ApiResponse</returns>
        public ApiResponse< ApiResponse > CreateSubscriptionWithHttpInfo (string statistics)
        {
            // verify the required parameter 'statistics' is set
            if (statistics == null)
                throw new ApiException(400, "Missing required parameter 'statistics' when calling StatisticsApi->CreateSubscription");

            var localVarPath = "/statistics/v3/subscriptions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (statistics != null && statistics.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(statistics); // http body (model) parameter
            }
            else
            {
                localVarPostBody = statistics; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateSubscription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse)));
        }

        /// <summary>
        /// Opens the stat server subscription for the specified set of statistics 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">definitions for statistics which are to be opened with stat server</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse> CreateSubscriptionAsync (string statistics)
        {
             ApiResponse<ApiResponse> localVarResponse = await CreateSubscriptionAsyncWithHttpInfo(statistics);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Opens the stat server subscription for the specified set of statistics 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">definitions for statistics which are to be opened with stat server</param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiResponse>> CreateSubscriptionAsyncWithHttpInfo (string statistics)
        {
            // verify the required parameter 'statistics' is set
            if (statistics == null)
                throw new ApiException(400, "Missing required parameter 'statistics' when calling StatisticsApi->CreateSubscription");

            var localVarPath = "/statistics/v3/subscriptions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (statistics != null && statistics.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(statistics); // http body (model) parameter
            }
            else
            {
                localVarPostBody = statistics; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateSubscription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse)));
        }

        /// <summary>
        /// Deletes the specified stat server subscription 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to delete</param>
        /// <returns>ApiResponse</returns>
        public ApiResponse DeleteSubscription (string id)
        {
             ApiResponse<ApiResponse> localVarResponse = DeleteSubscriptionWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Deletes the specified stat server subscription 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to delete</param>
        /// <returns>ApiResponse of ApiResponse</returns>
        public ApiResponse< ApiResponse > DeleteSubscriptionWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling StatisticsApi->DeleteSubscription");

            var localVarPath = "/statistics/v3/subscriptions/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteSubscription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse)));
        }

        /// <summary>
        /// Deletes the specified stat server subscription 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to delete</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse> DeleteSubscriptionAsync (string id)
        {
             ApiResponse<ApiResponse> localVarResponse = await DeleteSubscriptionAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Deletes the specified stat server subscription 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to delete</param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiResponse>> DeleteSubscriptionAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling StatisticsApi->DeleteSubscription");

            var localVarPath = "/statistics/v3/subscriptions/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteSubscription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse)));
        }

        /// <summary>
        /// Peeks the value of specified statistic 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statisticName">name of statistic to be peeked</param>
        /// <param name="objectId">id of object for which statistic to be peeked</param>
        /// <param name="objectType">type of object for which statistic to be peeked</param>
        /// <returns>ApiResponse</returns>
        public ApiResponse GetStatValue (string statisticName, string objectId, string objectType)
        {
             ApiResponse<ApiResponse> localVarResponse = GetStatValueWithHttpInfo(statisticName, objectId, objectType);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Peeks the value of specified statistic 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statisticName">name of statistic to be peeked</param>
        /// <param name="objectId">id of object for which statistic to be peeked</param>
        /// <param name="objectType">type of object for which statistic to be peeked</param>
        /// <returns>ApiResponse of ApiResponse</returns>
        public ApiResponse< ApiResponse > GetStatValueWithHttpInfo (string statisticName, string objectId, string objectType)
        {
            // verify the required parameter 'statisticName' is set
            if (statisticName == null)
                throw new ApiException(400, "Missing required parameter 'statisticName' when calling StatisticsApi->GetStatValue");
            // verify the required parameter 'objectId' is set
            if (objectId == null)
                throw new ApiException(400, "Missing required parameter 'objectId' when calling StatisticsApi->GetStatValue");
            // verify the required parameter 'objectType' is set
            if (objectType == null)
                throw new ApiException(400, "Missing required parameter 'objectType' when calling StatisticsApi->GetStatValue");

            var localVarPath = "/statistics/v3/statistic-values/{statisticName}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (statisticName != null) localVarPathParams.Add("statisticName", Configuration.ApiClient.ParameterToString(statisticName)); // path parameter
            if (objectId != null) localVarQueryParams.Add("objectId", Configuration.ApiClient.ParameterToString(objectId)); // query parameter
            if (objectType != null) localVarQueryParams.Add("objectType", Configuration.ApiClient.ParameterToString(objectType)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStatValue", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse)));
        }

        /// <summary>
        /// Peeks the value of specified statistic 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statisticName">name of statistic to be peeked</param>
        /// <param name="objectId">id of object for which statistic to be peeked</param>
        /// <param name="objectType">type of object for which statistic to be peeked</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse> GetStatValueAsync (string statisticName, string objectId, string objectType)
        {
             ApiResponse<ApiResponse> localVarResponse = await GetStatValueAsyncWithHttpInfo(statisticName, objectId, objectType);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Peeks the value of specified statistic 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statisticName">name of statistic to be peeked</param>
        /// <param name="objectId">id of object for which statistic to be peeked</param>
        /// <param name="objectType">type of object for which statistic to be peeked</param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiResponse>> GetStatValueAsyncWithHttpInfo (string statisticName, string objectId, string objectType)
        {
            // verify the required parameter 'statisticName' is set
            if (statisticName == null)
                throw new ApiException(400, "Missing required parameter 'statisticName' when calling StatisticsApi->GetStatValue");
            // verify the required parameter 'objectId' is set
            if (objectId == null)
                throw new ApiException(400, "Missing required parameter 'objectId' when calling StatisticsApi->GetStatValue");
            // verify the required parameter 'objectType' is set
            if (objectType == null)
                throw new ApiException(400, "Missing required parameter 'objectType' when calling StatisticsApi->GetStatValue");

            var localVarPath = "/statistics/v3/statistic-values/{statisticName}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (statisticName != null) localVarPathParams.Add("statisticName", Configuration.ApiClient.ParameterToString(statisticName)); // path parameter
            if (objectId != null) localVarQueryParams.Add("objectId", Configuration.ApiClient.ParameterToString(objectId)); // query parameter
            if (objectType != null) localVarQueryParams.Add("objectType", Configuration.ApiClient.ParameterToString(objectType)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStatValue", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse)));
        }

        /// <summary>
        /// Peeks the values of specified statistics 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">A set of definitions for statistics which are to be peeked from stat server</param>
        /// <returns>ApiResponse</returns>
        public ApiResponse GetStatValues (string statistics)
        {
             ApiResponse<ApiResponse> localVarResponse = GetStatValuesWithHttpInfo(statistics);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Peeks the values of specified statistics 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">A set of definitions for statistics which are to be peeked from stat server</param>
        /// <returns>ApiResponse of ApiResponse</returns>
        public ApiResponse< ApiResponse > GetStatValuesWithHttpInfo (string statistics)
        {
            // verify the required parameter 'statistics' is set
            if (statistics == null)
                throw new ApiException(400, "Missing required parameter 'statistics' when calling StatisticsApi->GetStatValues");

            var localVarPath = "/statistics/v3/operations/get-statistic-ex";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (statistics != null && statistics.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(statistics); // http body (model) parameter
            }
            else
            {
                localVarPostBody = statistics; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStatValues", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse)));
        }

        /// <summary>
        /// Peeks the values of specified statistics 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">A set of definitions for statistics which are to be peeked from stat server</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse> GetStatValuesAsync (string statistics)
        {
             ApiResponse<ApiResponse> localVarResponse = await GetStatValuesAsyncWithHttpInfo(statistics);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Peeks the values of specified statistics 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="statistics">A set of definitions for statistics which are to be peeked from stat server</param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiResponse>> GetStatValuesAsyncWithHttpInfo (string statistics)
        {
            // verify the required parameter 'statistics' is set
            if (statistics == null)
                throw new ApiException(400, "Missing required parameter 'statistics' when calling StatisticsApi->GetStatValues");

            var localVarPath = "/statistics/v3/operations/get-statistic-ex";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (statistics != null && statistics.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(statistics); // http body (model) parameter
            }
            else
            {
                localVarPostBody = statistics; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStatValues", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse)));
        }

        /// <summary>
        /// Peeks the values of statistics opened inside the specified subscription 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to peek</param>
        /// <param name="statisticIds">The ids of the statistics to peek (optional)</param>
        /// <returns>ApiResponse</returns>
        public ApiResponse PeekSubscriptionStats (string id, string statisticIds = null)
        {
             ApiResponse<ApiResponse> localVarResponse = PeekSubscriptionStatsWithHttpInfo(id, statisticIds);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Peeks the values of statistics opened inside the specified subscription 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to peek</param>
        /// <param name="statisticIds">The ids of the statistics to peek (optional)</param>
        /// <returns>ApiResponse of ApiResponse</returns>
        public ApiResponse< ApiResponse > PeekSubscriptionStatsWithHttpInfo (string id, string statisticIds = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling StatisticsApi->PeekSubscriptionStats");

            var localVarPath = "/statistics/v3/subscriptions/{id}/statistic-values";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (statisticIds != null) localVarQueryParams.Add("statisticIds", Configuration.ApiClient.ParameterToString(statisticIds)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PeekSubscriptionStats", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse)));
        }

        /// <summary>
        /// Peeks the values of statistics opened inside the specified subscription 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to peek</param>
        /// <param name="statisticIds">The ids of the statistics to peek (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse> PeekSubscriptionStatsAsync (string id, string statisticIds = null)
        {
             ApiResponse<ApiResponse> localVarResponse = await PeekSubscriptionStatsAsyncWithHttpInfo(id, statisticIds);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Peeks the values of statistics opened inside the specified subscription 
        /// </summary>
        /// <exception cref="Genesys.Statistics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The id of the subscription to peek</param>
        /// <param name="statisticIds">The ids of the statistics to peek (optional)</param>
        /// <returns>Task of ApiResponse (ApiResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiResponse>> PeekSubscriptionStatsAsyncWithHttpInfo (string id, string statisticIds = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling StatisticsApi->PeekSubscriptionStats");

            var localVarPath = "/statistics/v3/subscriptions/{id}/statistic-values";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (statisticIds != null) localVarQueryParams.Add("statisticIds", Configuration.ApiClient.ParameterToString(statisticIds)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PeekSubscriptionStats", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApiResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse)));
        }

    }
}
