/* 
 * Statistics Service
 *
 * Statistics Service
 *
 * OpenAPI spec version: 9.0.000.00.353
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Genesys.Statistics.Client.SwaggerDateConverter;

namespace Genesys.Statistics.Model
{
    /// <summary>
    /// PeekedStatisticValue
    /// </summary>
    [DataContract]
    public partial class PeekedStatisticValue :  IEquatable<PeekedStatisticValue>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PeekedStatisticValue" /> class.
        /// </summary>
        /// <param name="Name">name of statistic.</param>
        /// <param name="ObjectId">Id (in StatServer&#39;s terms) of object.</param>
        /// <param name="ObjectType">Stat type of object.</param>
        /// <param name="Timestamp">Timestamp when statistic was generated on StatServer.</param>
        /// <param name="Value">The value of statistic. Structure reflects the structure of StatServer message.</param>
        public PeekedStatisticValue(string Name = default(string), string ObjectId = default(string), string ObjectType = default(string), long? Timestamp = default(long?), Object Value = default(Object))
        {
            this.Name = Name;
            this.ObjectId = ObjectId;
            this.ObjectType = ObjectType;
            this.Timestamp = Timestamp;
            this.Value = Value;
        }
        
        /// <summary>
        /// name of statistic
        /// </summary>
        /// <value>name of statistic</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Id (in StatServer&#39;s terms) of object
        /// </summary>
        /// <value>Id (in StatServer&#39;s terms) of object</value>
        [DataMember(Name="objectId", EmitDefaultValue=false)]
        public string ObjectId { get; set; }

        /// <summary>
        /// Stat type of object
        /// </summary>
        /// <value>Stat type of object</value>
        [DataMember(Name="objectType", EmitDefaultValue=false)]
        public string ObjectType { get; set; }

        /// <summary>
        /// Timestamp when statistic was generated on StatServer
        /// </summary>
        /// <value>Timestamp when statistic was generated on StatServer</value>
        [DataMember(Name="timestamp", EmitDefaultValue=false)]
        public long? Timestamp { get; set; }

        /// <summary>
        /// The value of statistic. Structure reflects the structure of StatServer message
        /// </summary>
        /// <value>The value of statistic. Structure reflects the structure of StatServer message</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PeekedStatisticValue {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ObjectId: ").Append(ObjectId).Append("\n");
            sb.Append("  ObjectType: ").Append(ObjectType).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PeekedStatisticValue);
        }

        /// <summary>
        /// Returns true if PeekedStatisticValue instances are equal
        /// </summary>
        /// <param name="other">Instance of PeekedStatisticValue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PeekedStatisticValue other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.ObjectId == other.ObjectId ||
                    this.ObjectId != null &&
                    this.ObjectId.Equals(other.ObjectId)
                ) && 
                (
                    this.ObjectType == other.ObjectType ||
                    this.ObjectType != null &&
                    this.ObjectType.Equals(other.ObjectType)
                ) && 
                (
                    this.Timestamp == other.Timestamp ||
                    this.Timestamp != null &&
                    this.Timestamp.Equals(other.Timestamp)
                ) && 
                (
                    this.Value == other.Value ||
                    this.Value != null &&
                    this.Value.Equals(other.Value)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.ObjectId != null)
                    hash = hash * 59 + this.ObjectId.GetHashCode();
                if (this.ObjectType != null)
                    hash = hash * 59 + this.ObjectType.GetHashCode();
                if (this.Timestamp != null)
                    hash = hash * 59 + this.Timestamp.GetHashCode();
                if (this.Value != null)
                    hash = hash * 59 + this.Value.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
